name: test-workflow
run-name: "${{ github.actor }}-${{github.sha}}"
on:
  workflow_dispatch: 

jobs:
  nodejs-deploy:
      name: Deploy to Azure VM
      runs-on: ubuntu-latest
      
      steps:
      - name: Azure login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Stop and remove container
        run: |
          az vm run-command invoke \
            --resource-group beauty-app-rg \
            --name TestingVM \
            --command-id RunShellScript \
            --scripts "docker stop igor_front && docker rm igor_front"
  
      - name: Start container
        run: |
          az vm run-command invoke \
            --resource-group beauty-app-rg \
            --name TestingVM \
            --command-id RunShellScript \
            --scripts "docker run -d -p 5173:5173 --name igor_front andriis9/igor-frontend:1.0.5"
